export class Operator {
  constructor(
    type,
    statsType,
    statsDetail,
    matchesPlayed,
    roundsPlayed,
    minutesPlayed,
    matchesWon,
    matchesLost,
    roundsWon,
    roundsLost,
    kills,
    assists,
    death,
    headshots,
    meleeKills,
    teamKills,
    openingKills,
    openingDeaths,
    trades,
    openingKillTrades,
    openingDeathTrades,
    revives,
    distanceTravelled,
    winLossRatio,
    killDeathRatio,
    headshotAccuracy,
    killsPerRound,
    roundsWithAKill,
    roundsWithAMultiKill,
    roundsWithOpeningKill,
    roundsWithOpeningDeath,
    roundsWithKOST,
    roundsSurvived,
    roundsWithAnAce,
    roundsWithClutch,
    timeAlivePerMatch,
    timeDeadPerMatch,
    distancePerRound
  ) {
    (this.type = type),
      (this.statsType = statsType),
      (this.seasonNumber = seasonNumber),
      (this.matchesPlayed = matchesPlayed),
      (this.roundsPlayed = roundsPlayed),
      (this.minutesPlayed = minutesPlayed),
      (this.matchesWon = matchesWon),
      (this.matchesLost = matchesLost),
      (this.roundsWon = roundsWon),
      (this.roundsLost = roundsLost),
      (this.kills = kills),
      (this.assists = assists),
      (this.death = death),
      (this.headshots = headshots),
      (this.meleeKills = meleeKills),
      (this.teamKills = teamKills),
      (this.openingKills = openingKills),
      (this.openingDeaths = openingDeaths),
      (this.trades = trades),
      (this.openingKillTrades = openingKillTrades),
      (this.openingDeathTrades = openingDeathTrades),
      (this.revives = revives),
      (this.distanceTravelled = distanceTravelled),
      (this.winLossRatio = winLossRatio),
      (this.killDeathRatio = killDeathRatio),
      (this.headshotAccuracy = headshotAccuracy),
      (this.killsPerRound = killsPerRound),
      (this.roundsWithAKill = roundsWithAKill),
      (this.roundsWithAMultiKill = roundsWithAMultiKill),
      (this.roundsWithOpeningKill = roundsWithOpeningKill),
      (this.roundsWithOpeningDeath = roundsWithOpeningDeath),
      (this.roundsWithKOST = roundsWithKOST),
      (this.roundsSurvived = roundsSurvived),
      (this.roundsWithAnAce = roundsWithAnAce),
      (this.roundsWithClutch = roundsWithClutch),
      (this.timeAlivePerMatch = timeAlivePerMatch),
      (this.timeDeadPerMatch = timeDeadPerMatch),
      (this.distancePerRound = distancePerRound);
  }
}
