class UserRankDtoV1 {
  constructor(
    maxMMR,
    skillMean,
    deaths,
    profileId,
    nextRankMMR,
    rank,
    maxRank,
    boardId,
    skillStdev,
    kills,
    lastMatchSkillStdevChange,
    pastSeasonWins,
    updateTime,
    lastMatchMMRChange,
    abandons,
    season,
    pastSeasonsLosses,
    topRankPosition,
    lastMatchSkillMeanChange,
    MMR,
    previousRankMMR,
    lastMatchResult,
    pastSeasonsAbandons,
    wins,
    region,
    losses
  ) {
    (this.maxMMR = maxMMR), (this.skillMean = skillMean);
    (this.deaths = deaths),
      (this.profileId = profileId),
      (this.nextRankMMR = nextRankMMR),
      (this.rank = rank),
      (this.maxRank = maxRank),
      (this.boardId = boardId),
      (this.skillStdev = skillStdev),
      (this.kills = kills),
      (this.lastMatchSkillStdevChange = lastMatchSkillStdevChange),
      (this.pastSeasonWins = pastSeasonWins),
      (this.updateTime = updateTime),
      (this.lastMatchMMRChange = lastMatchMMRChange),
      (this.abandons = abandons),
      (this.season = season),
      (this.pastSeasonsLosses = pastSeasonsLosses),
      (this.topRankPosition = topRankPosition),
      (this.lastMatchSkillMeanChange = lastMatchSkillMeanChange),
      (this.MMR = MMR),
      (this.previousRankMMR = previousRankMMR),
      (this.lastMatchResult = lastMatchResult),
      (this.pastSeasonsAbandons = pastSeasonsAbandons),
      (this.wins = wins),
      (this.region = region),
      (this.losses = losses);
  }
}

export default UserRankDtoV1;
